apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# noinspection KubernetesMissingKeys
patches:
- path: env-vars.yaml
images:
- name: apples-service
  newName: ghcr.io/rw-gitops-demo/apples-service
  newTag: 1.0.5
