apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/source/path
      value: apples-service/envs/prod
  target:
    name: apples-service
