apiVersion: apps/v1
kind: Deployment
metadata:
  name: apples-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apples-service
  template:
    metadata:
      labels:
        app: apples-service
    spec:
      containers:
        - name: apples-service
          image: apples-service:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
